# This notebook aims to examine the personality scores for recruits and the respective departments that they have applied for.

## We imported the personality scores formatted as a .csv into a table

In [1]:
import pandas as pd
import numpy as np


personality_scores = pd.read_csv('datasets/personality_scores.csv', sep = ';')
personality_scores.head()

,ID,Section 5 of 6 [I am always prepared.],Section 5 of 6 [I am easily disturbed.],Section 5 of 6 [I am exacting (demanding) in my work.],Section 5 of 6 [I am full of ideas.],Section 5 of 6 [I am interested in people.],Section 5 of 6 [I am not interested in abstract ideas.],Section 5 of 6 [I am not interested in other people's problems.],Section 5 of 6 [I am not really interested in others.],Section 5 of 6 [I am quick to understand things.],...,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,IPIP_HIGH_RISK
0,0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Examine the data frame for duplicates

We don't want any duplicates within our table, and each record should be unique (based on ID), therefore we need to drop duplicate rows that exist as well as any null cells. We should also become aware of a change in number of rows, these could affect our end results largely and since each ID is unique, we should be notified if a record is missing.

In [2]:
clean_personality_scores = personality_scores.drop_duplicates('ID')
assert clean_personality_scores.shape[0] == personality_scores.ID.nunique(), 'lengths of dataframes are not the same'

Check for missing values.

In [3]:
print(clean_personality_scores.isnull().sum())

ID                                                           0
Section 5 of 6 [I am always prepared.]                       0
Section 5 of 6 [I am easily disturbed.]                      0
Section 5 of 6 [I am exacting (demanding) in my work.]       0
Section 5 of 6 [I am full of ideas.]                         0
                                                          ...
Unnamed: 65                                               1555
Unnamed: 66                                               1555
Unnamed: 67                                               1555
Unnamed: 68                                               1555
IPIP_HIGH_RISK                                            1555
Length: 70, dtype: int64

The majority of columns have Null values for the entire column, we should remove these, they provide no value.

In [4]:
clean_personality_scores = personality_scores.dropna(1)
clean_personality_scores

,ID,Section 5 of 6 [I am always prepared.],Section 5 of 6 [I am easily disturbed.],Section 5 of 6 [I am exacting (demanding) in my work.],Section 5 of 6 [I am full of ideas.],Section 5 of 6 [I am interested in people.],Section 5 of 6 [I am not interested in abstract ideas.],Section 5 of 6 [I am not interested in other people's problems.],Section 5 of 6 [I am not really interested in others.],Section 5 of 6 [I am quick to understand things.],...,Section 5 of 6 [I often forget to put things back in their proper place],Section 5 of 6 [I pay attention to details.],Section 5 of 6 [I seldom feel blue (down).],Section 5 of 6 [I spend time reflecting on things.],Section 5 of 6 [I start conversations.],Section 5 of 6 [I sympathize with others' feelings.],Section 5 of 6 [I take time out for others.],Section 5 of 6 [I talk to a lot of different people at parties.],Section 5 of 6 [I use difficult words.],Section 5 of 6 [I worry about things.]
0,0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,"(3, 5)","(3, 5)","(4, 3)","(5, 5)","(1, 3)","(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)"
1,1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)",...,"(3, 5)","(3, 1)","(4, 1)","(5, 5)","(1, 5)","(2, 5)","(2, 5)","(1, 5)","(5, 3)","(4, 3)"
2,2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,"(3, 5)","(3, 5)","(4, 1)","(5, 3)","(1, 3)","(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)"
3,3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)",...,"(3, 1)","(3, 5)","(4, 1)","(5, 5)","(1, 5)","(2, 5)","(2, 5)","(1, 5)","(5, 1)","(4, 1)"
4,4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)",...,"(3, 5)","(3, 5)","(4, 5)","(5, 5)","(1, 3)","(2, 3)","(2, 5)","(1, 3)","(5, 1)","(4, 3)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1550,1550,"(3, 5)","(4, 5)","(3, 1)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,"(3, 1)","(3, 5)","(4, 1)","(5, 3)","(1, 5)","(2, 5)","(2, 3)","(1, 1)","(5, 1)","(4, 5)"
1551,1551,"(3, 3)","(4, 5)","(3, 5)","(5, 3)","(2, 5)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,"(3, 3)","(3, 3)","(4, 1)","(5, 3)","(1, 3)","(2, 5)","(2, 5)","(1, 5)","(5, 1)","(4, 3)"
1552,1552,"(3, 5)","(4, 3)","(3, 5)","(5, 5)","(2, 5)","(5, 5)","(2, 3)","(2, 3)","(5, 5)",...,"(3, 3)","(3, 5)","(4, 5)","(5, 5)","(1, 5)","(2, 5)","(2, 5)","(1, 5)","(5, 3)","(4, 3)"
1553,1553,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,"(3, 5)","(3, 5)","(4, 1)","(5, 5)","(1, 5)","(2, 3)","(2, 3)","(1, 1)","(5, 1)","(4, 3)"
1554,1554,"(3, 3)","(4, 5)","(3, 1)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 5)","(5, 3)",...,"(3, 5)","(3, 5)","(4, 3)","(5, 3)","(1, 3)","(2, 5)","(2, 3)","(1, 1)","(5, 1)","(4, 3)"

As seen in the previous table, the name of the headings all contain redundant strings, namely: 'Section 5 of 6 \[ \]', we need to remove them.

In [5]:
new_columns =[]
for column in clean_personality_scores.columns:
    column = column.replace('Section 5 of 6 [', '')
    column = column.replace(']', '')
    new_columns.append(column)
clean_personality_scores.columns = new_columns
clean_personality_scores.head()

,ID,I am always prepared.,I am easily disturbed.,I am exacting (demanding) in my work.,I am full of ideas.,I am interested in people.,I am not interested in abstract ideas.,I am not interested in other people's problems.,I am not really interested in others.,I am quick to understand things.,...,I often forget to put things back in their proper place,I pay attention to details.,I seldom feel blue (down).,I spend time reflecting on things.,I start conversations.,I sympathize with others' feelings.,I take time out for others.,I talk to a lot of different people at parties.,I use difficult words.,I worry about things.
0,0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)",...,"(3, 5)","(3, 5)","(4, 3)","(5, 5)","(1, 3)","(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)"
1,1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)",...,"(3, 5)","(3, 1)","(4, 1)","(5, 5)","(1, 5)","(2, 5)","(2, 5)","(1, 5)","(5, 3)","(4, 3)"
2,2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)",...,"(3, 5)","(3, 5)","(4, 1)","(5, 3)","(1, 3)","(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)"
3,3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)",...,"(3, 1)","(3, 5)","(4, 1)","(5, 5)","(1, 5)","(2, 5)","(2, 5)","(1, 5)","(5, 1)","(4, 1)"
4,4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)",...,"(3, 5)","(3, 5)","(4, 5)","(5, 5)","(1, 3)","(2, 3)","(2, 5)","(1, 3)","(5, 1)","(4, 3)"

## Questionnaire scoring
The test consists of fifty items rated agree, neutral or disagree. To keep scoring consistent with the
original five point scale, items are scored 1=Disagree, 3=Neutral and 5=Agree.

Scores are saved as tuples. The first value of the tuple always indicates the subscale to which the item belongs:
1 = Extraversion, 2 = Agreeableness, 3 = Conscientiousness, 4 = Emotional Stability/Neuroticism, and 5 = Intellect/Imagination / openness to experiences).
The second value in the tuple indicates the individual's scored response to that question (i.e., 1=Disagree, 3=Neutral and 5=Agree).

Sum all of the individual's responses within a subscale (e.g. extraversion) to obtain a total subscale score.
In other words, the second number in the tuple should be scored for all columns with the same number in the first position (1 indicates extraversion, for example)

In [6]:
# ignoring the Id column cos we've checked for duplicates
clean_personality_scores.set_index('ID', inplace=True)

### Create new columns containing the total score of each of the personality test subscales.

In [7]:
def score_of_each_category(row):
    extraversion, agreeable, conscientiousness, emotional_stability, intellect = 0,0,0,0,0
    for cell in row:
        clean_cell = cell.strip('(')
        clean_cell = clean_cell.strip(')')
        clean_cell = clean_cell.replace(' ', '')
        
        category = int(clean_cell[0])
        
        if category == 1:
            extraversion += int(clean_cell[-1])
        elif category == 2:
            agreeable += int(clean_cell[-1])
        elif category == 3:
            conscientiousness += int(clean_cell[-1])
        elif category == 4:
            emotional_stability += int(clean_cell[-1])
        elif category == 5:
            intellect += int(clean_cell[-1])
    return extraversion, agreeable, conscientiousness, emotional_stability, intellect

score_list = [x for x in clean_personality_scores.apply(score_of_each_category, axis=1)]
score_df = pd.DataFrame(score_list, columns= ['extraversion', 'agreeable', 'conscientiousness'
                                                                            ,'emotional_stability', 'intellect'])

personality_scores = pd.concat([clean_personality_scores, score_df], axis=1)
personality_scores

,I am always prepared.,I am easily disturbed.,I am exacting (demanding) in my work.,I am full of ideas.,I am interested in people.,I am not interested in abstract ideas.,I am not interested in other people's problems.,I am not really interested in others.,I am quick to understand things.,I am quiet around strangers.,...,I sympathize with others' feelings.,I take time out for others.,I talk to a lot of different people at parties.,I use difficult words.,I worry about things.,extraversion,agreeable,conscientiousness,emotional_stability,intellect
0,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 3)","(5, 3)","(2, 3)","(2, 5)","(5, 5)","(1, 3)",...,"(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)",30,40,48,36,42
1,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 3)","(2, 5)","(2, 5)","(5, 5)","(1, 3)",...,"(2, 5)","(2, 5)","(1, 5)","(5, 3)","(4, 3)",42,46,46,40,42
2,"(3, 5)","(4, 3)","(3, 3)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)","(1, 1)",...,"(2, 5)","(2, 5)","(1, 3)","(5, 1)","(4, 3)",28,40,40,38,42
3,"(3, 5)","(4, 5)","(3, 3)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 3)","(5, 3)","(1, 3)",...,"(2, 5)","(2, 5)","(1, 5)","(5, 1)","(4, 1)",30,38,38,40,38
4,"(3, 3)","(4, 5)","(3, 3)","(5, 3)","(2, 3)","(5, 3)","(2, 3)","(2, 3)","(5, 5)","(1, 1)",...,"(2, 3)","(2, 5)","(1, 3)","(5, 1)","(4, 3)",28,34,46,38,36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1550,"(3, 5)","(4, 5)","(3, 1)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)","(1, 3)",...,"(2, 5)","(2, 3)","(1, 1)","(5, 1)","(4, 5)",32,48,38,44,44
1551,"(3, 3)","(4, 5)","(3, 5)","(5, 3)","(2, 5)","(5, 3)","(2, 3)","(2, 5)","(5, 5)","(1, 5)",...,"(2, 5)","(2, 5)","(1, 5)","(5, 1)","(4, 3)",40,48,40,44,34
1552,"(3, 5)","(4, 3)","(3, 5)","(5, 5)","(2, 5)","(5, 5)","(2, 3)","(2, 3)","(5, 5)","(1, 3)",...,"(2, 5)","(2, 5)","(1, 5)","(5, 3)","(4, 3)",42,44,40,46,48
1553,"(3, 5)","(4, 5)","(3, 5)","(5, 5)","(2, 5)","(5, 5)","(2, 5)","(2, 5)","(5, 5)","(1, 5)",...,"(2, 3)","(2, 3)","(1, 1)","(5, 1)","(4, 3)",36,38,48,36,44
1554,"(3, 3)","(4, 5)","(3, 1)","(5, 5)","(2, 5)","(5, 3)","(2, 3)","(2, 5)","(5, 3)","(1, 3)",...,"(2, 5)","(2, 3)","(1, 1)","(5, 1)","(4, 3)",22,44,42,40,30

## We want to import the department data

In [8]:
department = pd.read_csv('datasets/departments.csv', sep=';', index_col= 'ID')
department.head()

   Department
ID
0        Data
1        Data
2        Data
3        Data
4        Data

We should look at the various departments the recruits have joined

In [9]:
department.Department.unique()

array(['Data', 'Web Dev', 'Copywriting', 'Design', 'Strategy', 'Web dev'],
      dtype=object)

While scanning the departments data, we realize that there are duplicates namely: 'Web Dev' and 'Web dev', this ideally should have same characters, we need to change one or the other. We remove the duplicates for correctness of our results, without correction it would mean that we have six departments when we actually have five.

In [10]:
department['Department'] = department['Department'].str.replace('Web dev', 'Web Dev')
department.Department.unique()

array(['Data', 'Web Dev', 'Copywriting', 'Design', 'Strategy'],
      dtype=object)

In [11]:
personality_scores_department = pd.concat([personality_scores, department], axis=1)

assert len((personality_scores_department)) == len((department)), 'lengths of dataframes are not the same'
assert (personality_scores_department.shape[1]) == (personality_scores.shape[1] + department.shape[1]), 'length of columns are not the same'

Filter the merged data frame so that you get only the applicants who scored less than 30 on emotional stability, conscientiousness AND agreeableness. Print the ID numbers and departments of these applicants to the screen, and also assign these applicants the tag “high_risk” in a new column. All other applicants get the tag “low_risk”

In [12]:
smaller_than_thirty = personality_scores_department[(personality_scores_department['emotional_stability'] < 30) & 
                    (personality_scores_department['conscientiousness'] < 30) & (personality_scores_department['agreeable'] < 30)]
smaller_than_thirty['Department']

881            Data
1197    Copywriting
Name: Department, dtype: object

Assign the applicants 'high_risk' in a new column and the other applicants 'low_risk'

In [13]:
personality_scores_department['Risk'] = np.where((personality_scores_department['emotional_stability'] < 30) & 
                            (personality_scores_department['conscientiousness'] < 30) & (personality_scores_department['agreeable'] < 30), 
                            'high_risk', 'low_risk')

### Create a new data frame with a count of the number of low and high risk applicants within each department. Let each department be a separate column.

In [14]:
personality_scores_department[['Risk', 'Department']].pivot_table(index='Risk', columns='Department', aggfunc=len, fill_value=0)

Department  Copywriting  Data  Design  Strategy  Web Dev
Risk
high_risk             1     1       0         0        0
low_risk            325   328     120       449      331

We only have two recruits classified as high risk